spring.application.name=authentication-service
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.username=root
spring.datasource.password=2234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.security.user.name=root
#spring.security.user.password=2234

#logging.level.org.springframework.security=TRACE
#logging.level.org.springframework.web=TRACE

# ===========================
# JWT Configuration
# ===========================

#jwt.secret=MyVeryStrongSecretKeyForABCAuthenticationService2026
#jwt.expiration=3600000
#jwt.issuer=authentication-service

jwt.secret=$2a$15$yAxUW8V3YJ/PUi/tiBO0s.hjH6e1c7oNC.yL7zxmijYi98p7xl3oy
jwt.issuer=authentication-service
# 15 minutes
jwt.access-token-expiration=900000
# 7 days
jwt.refresh-token-expiration=604800000

# ============================================================
# Mail Configuration
# ============================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=realityoflife012@gmail.com
spring.mail.password=bbzv ptce ytxf ldph

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ============================================================
# Frontend URL
# ============================================================

application.frontend.base-url=http://127.0.0.1:5500